// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4evl3BDKHsP_Mlip4F2WVY4Cst8WQe6s',
    appId: '1:1002739295443:web:8d578e012954c05490a026',
    messagingSenderId: '1002739295443',
    projectId: 'decisionmaker-fe29b',
    authDomain: 'decisionmaker-fe29b.firebaseapp.com',
    storageBucket: 'decisionmaker-fe29b.firebasestorage.app',
    measurementId: 'G-E5Q4VGENKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLFEf9UieEkneWCMjGv8bOgEedwXKA0E',
    appId: '1:1002739295443:android:c7af4a59c67f36e790a026',
    messagingSenderId: '1002739295443',
    projectId: 'decisionmaker-fe29b',
    storageBucket: 'decisionmaker-fe29b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0uquhOn06m6VKvWpxVV4isEqFjGSwQOs',
    appId: '1:1002739295443:ios:3bee6393de04ad6e90a026',
    messagingSenderId: '1002739295443',
    projectId: 'decisionmaker-fe29b',
    storageBucket: 'decisionmaker-fe29b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0uquhOn06m6VKvWpxVV4isEqFjGSwQOs',
    appId: '1:1002739295443:ios:3bee6393de04ad6e90a026',
    messagingSenderId: '1002739295443',
    projectId: 'decisionmaker-fe29b',
    storageBucket: 'decisionmaker-fe29b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4evl3BDKHsP_Mlip4F2WVY4Cst8WQe6s',
    appId: '1:1002739295443:web:c50c9746d71c3a6190a026',
    messagingSenderId: '1002739295443',
    projectId: 'decisionmaker-fe29b',
    authDomain: 'decisionmaker-fe29b.firebaseapp.com',
    storageBucket: 'decisionmaker-fe29b.firebasestorage.app',
    measurementId: 'G-45KH3RSB4C',
  );
}
